driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: server
    run_list:
      - recipe[npm_lazy::server]
    attributes:

  - name: client
    run_list:
      - recipe[npm_lazy::client]
    attributes:
      npm_lazy:
        client:
          install_nodejs: true
